version: "3.9"
services:
  web:
    build: 
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: 
      - sh
      - -c
      - "pnpm dev --host"